name: Update Streams docs

concurrency:
  group: Streams-norelease

on:
  push:
    branches:
      - main
    paths:
      - 'tiddlers/**'
    tags-ignore:
      - v[012].[0-9]+.[0-9]+
  workflow_dispatch:
  
jobs:
  deploy:
    if:  ${{ !contains(toJSON(github.event.commits.*.message), 'RELEASE') }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        
      - name: Checkout @latest
        uses: actions/checkout@v2
        with:
          ref: latest
          path: latest
        
      - name: Copy @latest Streams plugin
        run: |
          rm -fr ./plugins/streams
          mv -f ./latest/plugins/streams ./plugins/
        
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install Dependency
        run: npm install
      - name: Build
        run: |
            npm run build
            npm run build-prerelease

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output
          keep_files: true
